export const defaultWheel = {
  id: 'default',
  name: '今日干饭吃点啥',
  options: [
    { name: '火锅 / 串串', color: '#FF6B6B' },
    { name: '面食 / 粉类', color: '#4ECDC4' },
    { name: '米饭盖浇饭', color: '#45B7D1' },
    { name: '小吃 / 卤味', color: '#96CEB4' },
    { name: '麻辣烫 / 冒菜', color: '#FFEAA7' },
    { name: '汉堡 / 炸鸡', color: '#DDA0DD' },
    { name: '轻食 / 沙拉', color: '#98D8C8' },
    { name: '馄饨 / 水饺', color: '#F7DC6F' },
    { name: '螺蛳粉 / 花甲粉', color: '#BB8FCE' },
    { name: '日式简餐 / 寿司', color: '#85C1E9' },
    { name: '韩式拌饭 / 部队锅', color: '#F1948A' },
    { name: '烧烤 / 烤串', color: '#82E0AA' },
    { name: '蒸菜 / 煲仔饭', color: '#F8C471' },
    { name: '蛋包饭 / 焗饭', color: '#D2B4DE' },
    { name: '手抓饼 / 煎饼果子', color: '#A3E4D7' }
  ]
}

export const presetWheels = [
  {
    id: 'leisure',
    name: '休闲时光怎么过',
    options: [
      { name: '宅家追剧', color: '#FF6B6B' },
      { name: '打休闲游戏', color: '#4ECDC4' },
      { name: '听音乐放松', color: '#45B7D1' },
      { name: '看综艺 / 动漫', color: '#96CEB4' },
      { name: '读课外书籍', color: '#FFEAA7' },
      { name: '拼乐高 / 做手工', color: '#DDA0DD' },
      { name: '阳台晒太阳', color: '#98D8C8' },
      { name: '刷短视频', color: '#F7DC6F' },
      { name: '公园散步 / 遛弯', color: '#BB8FCE' },
      { name: '江边 / 湖边吹风', color: '#85C1E9' },
      { name: '居家烘焙 / 做甜品', color: '#F1948A' },
      { name: '养花种草 / 浇花', color: '#82E0AA' },
      { name: '拼拼图 / 玩积木', color: '#F8C471' },
      { name: '看纪录片 / 公开课', color: '#D2B4DE' },
      { name: '听播客 / 有声书', color: '#A3E4D7' }
    ]
  },
  {
    id: 'party',
    name: '聚会破冰小玩法',
    options: [
      { name: '真心话大冒险', color: '#FF6B6B' },
      { name: '谁是卧底', color: '#4ECDC4' },
      { name: '成语接龙', color: '#45B7D1' },
      { name: '猜拳大挑战', color: '#96CEB4' },
      { name: '你画我猜', color: '#FFEAA7' },
      { name: '真心话问答', color: '#DDA0DD' },
      { name: '数字炸弹', color: '#98D8C8' },
      { name: '词语接龙', color: '#F7DC6F' },
      { name: '简易版狼人杀', color: '#BB8FCE' },
      { name: '害你在心口难开', color: '#85C1E9' },
      { name: '真心话接力', color: '#F1948A' },
      { name: '猜歌名 / 接歌词', color: '#82E0AA' },
      { name: '逛三园', color: '#F8C471' },
      { name: '成语飞花令', color: '#D2B4DE' },
      { name: '绕口令挑战', color: '#A3E4D7' }
    ]
  },
  {
    id: 'couple',
    name: '情侣日常小美好',
    options: [
      { name: '牵手散步半小时', color: '#FF6B6B' },
      { name: '一起拼一张小拼图', color: '#4ECDC4' },
      { name: '互相分享今日趣事', color: '#45B7D1' },
      { name: '窝在一起看部甜剧', color: '#96CEB4' },
      { name: '一起做一顿家常菜', color: '#FFEAA7' },
      { name: '给对方捏捏肩揉揉背', color: '#DDA0DD' },
      { name: '互相拍几张可爱照片', color: '#98D8C8' },
      { name: '一起逛超市挑零食', color: '#F7DC6F' },
      { name: '对着对方说句土味情话', color: '#BB8FCE' },
      { name: '一起追同一部综艺', color: '#85C1E9' },
      { name: '手牵手压马路看夜景', color: '#F1948A' },
      { name: '互相投喂小零食', color: '#82E0AA' },
      { name: '一起玩一局双人小游戏', color: '#F8C471' },
      { name: '窝在沙发上聊未来', color: '#D2B4DE' },
      { name: '一起打卡街边小甜品', color: '#A3E4D7' }
    ]
  },
  {
    id: 'weekend',
    name: '周末去哪逛一逛',
    options: [
      { name: '逛城市公园喂鸽子', color: '#FF6B6B' },
      { name: '打卡网红文创街区', color: '#4ECDC4' },
      { name: '去图书馆泡一下午', color: '#45B7D1' },
      { name: '逛商场看新上映电影', color: '#96CEB4' },
      { name: '近郊爬山看风景', color: '#FFEAA7' },
      { name: '去花鸟市场逛一逛', color: '#DDA0DD' },
      { name: '打卡小众咖啡馆', color: '#98D8C8' },
      { name: '去科技馆 / 博物馆', color: '#F7DC6F' },
      { name: '逛夜市吃特色小吃', color: '#BB8FCE' },
      { name: '去湖边划船 / 散步', color: '#85C1E9' },
      { name: '打卡网红书店看书', color: '#F1948A' },
      { name: '去郊野营地搭帐篷', color: '#82E0AA' },
      { name: '逛动物园 / 植物园', color: '#F8C471' },
      { name: '去手工馆做 DIY 手作', color: '#D2B4DE' },
      { name: '逛农贸市集挑新鲜食材', color: '#A3E4D7' }
    ]
  },
  {
    id: 'punishment',
    name: '聚会轻罚小趣味',
    options: [
      { name: '学小猫叫三声并蹭身边人一下', color: '#FF6B6B' },
      { name: '用夹子音说一句 "大家好我是小可爱"', color: '#4ECDC4' },
      { name: '举手机自拍一张搞怪丑照发群里', color: '#45B7D1' },
      { name: '给在场所有人说一句简单彩虹屁', color: '#96CEB4' },
      { name: '学大猩猩走一圈并拍胸脯两次', color: '#FFEAA7' },
      { name: '喝一口桌上的饮品（无饮品则抿嘴三下）', color: '#DDA0DD' },
      { name: '对着窗外大喊一声 "今天真开心"', color: '#98D8C8' },
      { name: '模仿表情包做一个搞怪动作保持 10 秒', color: '#F7DC6F' },
      { name: '用嘴叼着笔写自己的名字', color: '#BB8FCE' },
      { name: '和身边人石头剪刀布输了弹一下脑门', color: '#85C1E9' },
      { name: '唱一句儿歌并做一个对应动作', color: '#F1948A' },
      { name: '说出自己的一个小糗事', color: '#82E0AA' },
      { name: '拍一下自己的大腿喊三声 "我错了"', color: '#F8C471' },
      { name: '帮身边人捏捏肩膀 10 秒钟', color: '#D2B4DE' },
      { name: '用方言说一句 "今天聚会太好玩了"', color: '#A3E4D7' }
    ]
  },
  {
    id: 'reward',
    name: '完成小事犒劳自己',
    options: [
      { name: '吃一块小蛋糕 / 甜品', color: '#FF6B6B' },
      { name: '喝一杯喜欢的奶茶 / 咖啡', color: '#4ECDC4' },
      { name: '追一集喜欢的剧 / 综艺', color: '#45B7D1' },
      { name: '刷 10 分钟短视频放松', color: '#96CEB4' },
      { name: '买一个心仪的小饰品 / 小物件', color: '#FFEAA7' },
      { name: '窝在沙发上发呆 20 分钟', color: '#DDA0DD' },
      { name: '吃一包喜欢的零食', color: '#98D8C8' },
      { name: '听半小时喜欢的歌单', color: '#F7DC6F' },
      { name: '泡一杯好喝的果茶 / 花茶', color: '#BB8FCE' },
      { name: '看一本喜欢的书半小时', color: '#85C1E9' },
      { name: '做一次简易面部护肤', color: '#F1948A' },
      { name: '玩一局喜欢的休闲游戏', color: '#82E0AA' },
      { name: '出门散步买一根冰淇淋', color: '#F8C471' },
      { name: '躺着听一段有声书 / 播客', color: '#D2B4DE' },
      { name: '给自己点一份喜欢的小吃', color: '#A3E4D7' }
    ]
  },
  {
    id: 'winner',
    name: '聚会赢家小福利',
    options: [
      { name: '让在场一人帮你拿一次饮品', color: '#FF6B6B' },
      { name: '让身边人给你唱一句生日快乐歌', color: '#4ECDC4' },
      { name: '让在场一人讲一个冷笑话', color: '#45B7D1' },
      { name: '让身边人帮你捏捏胳膊 10 秒', color: '#96CEB4' },
      { name: '免做一次聚会小任务（递纸巾 / 开瓶盖）', color: '#FFEAA7' },
      { name: '让在场一人模仿你的一个动作', color: '#DDA0DD' },
      { name: '喝到在场一人递的一口饮品', color: '#98D8C8' },
      { name: '让身边人说一个你的优点', color: '#F7DC6F' },
      { name: '让在场一人陪你玩一局石头剪刀布', color: '#BB8FCE' },
      { name: '收到在场一人的一个小祝福', color: '#85C1E9' },
      { name: '让身边人帮你拍一张好看的照片', color: '#F1948A' },
      { name: '让在场一人跟你一起比心拍照', color: '#82E0AA' },
      { name: '免答一次真心话问题', color: '#F8C471' },
      { name: '让身边人给你讲一个小趣事', color: '#D2B4DE' },
      { name: '收到在场一人分享的一块小零食', color: '#A3E4D7' }
    ]
  },
  {
    id: 'honor_of_kings',
    name: '王者荣耀随机选英雄',
    options: [
      { name: '白起', color: '#FF6B6B' },
      { name: '程咬金', color: '#FF8E53' },
      { name: '东皇太一', color: '#FFA07A' },
      { name: '项羽', color: '#FFB347' },
      { name: '廉颇', color: '#FFCC33' },
      { name: '刘邦', color: '#FFD700' },
      { name: '刘禅', color: '#FFE4B5' },
      { name: '牛魔', color: '#FFEFD5' },
      { name: '苏烈', color: '#FFF8DC' },
      { name: '张飞', color: '#FAF0E6' },
      { name: '钟馗', color: '#F5F5DC' },
      { name: '庄周', color: '#FFFAF0' },
      { name: '夏侯惇', color: '#F0FFF0' },
      { name: '亚瑟', color: '#E0FFFF' },
      { name: '钟无艳', color: '#AFEEEE' },
      { name: '蒙恬', color: '#7FFFD4' },
      { name: '盾山', color: '#40E0D0' },
      { name: '曹操', color: '#48D1CC' },
      { name: '典韦', color: '#00CED1' },
      { name: '宫本武藏', color: '#20B2AA' },
      { name: '关羽', color: '#008B8B' },
      { name: '花木兰', color: '#008080' },
      { name: '铠', color: '#66CDAA' },
      { name: '狂铁', color: '#3CB371' },
      { name: '老夫子', color: '#2E8B57' },
      { name: '李信', color: '#98FB98' },
      { name: '刘备', color: '#90EE90' },
      { name: '露娜', color: '#00FF7F' },
      { name: '吕布', color: '#00FA9A' },
      { name: '马超', color: '#7CFC00' },
      { name: '哪吒', color: '#ADFF2F' },
      { name: '盘古', color: '#32CD32' },
      { name: '裴擒虎', color: '#9ACD32' },
      { name: '孙策', color: '#6B8E23' },
      { name: '孙悟空', color: '#556B2F' },
      { name: '杨戬', color: '#BDB76B' },
      { name: '曜', color: '#FFFF00' },
      { name: '赵云', color: '#FFFACD' },
      { name: '达摩', color: '#FFE4C4' },
      { name: '夏洛特', color: '#FFDEAD' },
      { name: '司空震', color: '#FFDAB9' },
      { name: '云缨', color: '#FFC0CB' },
      { name: '橘右京', color: '#FFB6C1' },
      { name: '雅典娜', color: '#FF69B4' },
      { name: '阿轲', color: '#FF1493' },
      { name: '百里玄策', color: '#C71585' },
      { name: '不知火舞', color: '#DB7093' },
      { name: '兰陵王', color: '#FF6347' },
      { name: '李白', color: '#FF4500' },
      { name: '娜可露露', color: '#FFA500' },
      { name: '上官婉儿', color: '#FF8C00' },
      { name: '司马懿', color: '#FF7F50' },
      { name: '元歌', color: '#FF6347' },
      { name: '云中君', color: '#FF4500' },
      { name: '镜', color: '#DC143C' },
      { name: '澜', color: '#B22222' },
      { name: '安琪拉', color: '#FF6B6B' },
      { name: '扁鹊', color: '#FF69B4' },
      { name: '嫦娥', color: '#DA70D6' },
      { name: '妲己', color: '#BA55D3' },
      { name: '貂蝉', color: '#9370DB' },
      { name: '干将莫邪', color: '#8A2BE2' },
      { name: '高渐离', color: '#7B68EE' },
      { name: '海诺', color: '#6A5ACD' },
      { name: '海月', color: '#483D8B' },
      { name: '姜子牙', color: '#4B0082' },
      { name: '金蝉', color: '#9400D3' },
      { name: '米莱狄', color: '#8B008B' },
      { name: '芈月', color: '#800080' },
      { name: '墨子', color: '#9932CC' },
      { name: '女娲', color: '#BA55D3' },
      { name: '沈梦溪', color: '#DA70D6' },
      { name: '王昭君', color: '#EE82EE' },
      { name: '武则天', color: '#FF00FF' },
      { name: '西施', color: '#FF69B4' },
      { name: '小乔', color: '#FF1493' },
      { name: '杨玉环', color: '#C71585' },
      { name: '弈星', color: '#DB7093' },
      { name: '嬴政', color: '#FF6347' },
      { name: '张良', color: '#FF4500' },
      { name: '甄姬', color: '#FFA500' },
      { name: '周瑜', color: '#FF8C00' },
      { name: '诸葛亮', color: '#FF7F50' },
      { name: '梦奇', color: '#FF6347' },
      { name: '元流之子', color: '#FF4500' },
      { name: '艾琳', color: '#DC143C' },
      { name: '百里守约', color: '#B22222' },
      { name: '成吉思汗', color: '#FF6B6B' },
      { name: '狄仁杰', color: '#FF69B4' },
      { name: '伽罗', color: '#DA70D6' },
      { name: '公孙离', color: '#BA55D3' },
      { name: '黄忠', color: '#9370DB' },
      { name: '后羿', color: '#8A2BE2' },
      { name: '李元芳', color: '#7B68EE' },
      { name: '鲁班七号', color: '#6A5ACD' },
      { name: '马可波罗', color: '#483D8B' },
      { name: '孙尚香', color: '#4B0082' },
      { name: '虞姬', color: '#9400D3' },
      { name: '戈娅', color: '#8B008B' },
      { name: '蒙犽', color: '#800080' },
      { name: '莱西奥', color: '#9932CC' },
      { name: '蔡文姬', color: '#BA55D3' },
      { name: '大乔', color: '#DA70D6' },
      { name: '鬼谷子', color: '#EE82EE' },
      { name: '明世隐', color: '#FF00FF' },
      { name: '孙膑', color: '#FF69B4' },
      { name: '太乙真人', color: '#FF1493' },
      { name: '瑶', color: '#C71585' },
      { name: '鲁班大师', color: '#DB7093' },
      { name: '桑启', color: '#FF6347' },
      { name: '阿古朵', color: '#FF4500' },
      { name: '苍', color: '#FFA500' },
      { name: '大禹', color: '#FF8C00' },
      { name: '敖隐', color: '#FF7F50' },
      { name: '赵怀真', color: '#FF6347' },
      { name: '暃', color: '#FF4500' }
    ]
  }
]

export function generateColor(index, total) {
  const hue = (index * 360) / total
  return `hsl(${hue}, 70%, 60%)`
}

export function validateOptions(options) {
  if (!options || options.length < 2) {
    return { valid: false, message: '至少需要2个选项' }
  }
  
  for (let i = 0; i < options.length; i++) {
    if (!options[i].name || options[i].name.trim() === '') {
      return { valid: false, message: `第${i + 1}个选项名称不能为空` }
    }
  }
  
  return { valid: true }
}